/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaregistromuseos.Vistas;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import sistemaregistromuseos.Modelos.RegistroManager;

/**
 *
 * @author a-ntt
 */
public class AnulacionFrame extends javax.swing.JFrame {
    private JPanel mainPanel;
    private JTextField txtCodigo;
    private JTextArea txtMotivo;
    private JButton btnAnular;
    private RegistroManager registroManager;

    /**
     * Creates new form AnulacionFrame
     */
    public AnulacionFrame(RegistroManager registroManager) {
        this.registroManager = registroManager;
        setupFrame();
    }
    
    private void setupFrame() {
        setTitle("Anulación de Registros");
        setSize(500, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        // Limpiar contenido existente
        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout());
        
        createComponents();
        setupLayout();
        setupEventHandlers();
        
        revalidate();
        repaint();
    }

    private void createComponents() {
        mainPanel = new JPanel(new GridLayout(0, 1, 10, 10));
        
        txtCodigo = new JTextField();
        txtMotivo = new JTextArea(5, 20);
        txtMotivo.setLineWrap(true);
        txtMotivo.setWrapStyleWord(true);
        
        btnAnular = new JButton("Anular Registro");
    }

    private void setupLayout() {
        JPanel formPanel = new JPanel(new GridLayout(0, 1, 5, 5));
        
        formPanel.add(new JLabel("Código de Visita a Anular:"));
        formPanel.add(txtCodigo);
        formPanel.add(new JLabel("Motivo de Anulación (obligatorio):"));
        formPanel.add(new JScrollPane(txtMotivo));
        
        mainPanel.add(formPanel);
        mainPanel.add(btnAnular);
        
        getContentPane().add(mainPanel, BorderLayout.CENTER);
    }

    private void setupEventHandlers() {
        btnAnular.addActionListener(e -> anularRegistro());
    }

    private void anularRegistro() {
        String codigo = txtCodigo.getText().trim();
        String motivo = txtMotivo.getText().trim();
        
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Debe ingresar un código de visita",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (motivo.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Debe ingresar un motivo de anulación",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            registroManager.anularRegistro(codigo, motivo);
            
            JOptionPane.showMessageDialog(this,
                "Registro anulado exitosamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            limpiarFormulario();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al anular registro: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void limpiarFormulario() {
        txtCodigo.setText("");
        txtMotivo.setText("");
        txtCodigo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnulacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnulacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnulacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnulacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Crear una instancia de RegistroManager para pasar al frame
                RegistroManager registroManager = new RegistroManager();
                new AnulacionFrame(registroManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
